openapi: "3.0.1"
info:
  title: "API Gateway HTTP API to EventBridge"
  version: "1"
paths:
  /send-to-eventbridge:
    post:
      responses:
        default:
          description: "EventBridge response"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"
        credentials:
          Fn::GetAtt: [HttpApiRole, Arn]
        requestParameters:
          Detail: "$request.body.Detail"
          DetailType: MyDetailType
          Source: MyCustomEvent
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"